#ifndef PRIORITIES_H
#define PRIORITIES_H

#define RESPONDER_TASK_PRIORITY (9)
#define CONTROLLER_TASK_PRIORITY (8)
#define DISPLAY_TASK_PRIORITY (16)
#define UART_TASK_PRIORITY (4)
#define TIMER_PRIORITY (24)

#endif // PRIORITIES_H